const std = @import("std");
const c = @import("../../imports.zig");

pub const Keys = enum(u8) {
    // Modifiers first
    Key_LCTRL = 0b00000000,
    Key_LSHIFT,
    Key_LALT,
    Key_LGUI,
    Key_RCTRL,
    Key_RSHIFT,
    Key_RALT,
    Key_RGUI,
    Key_MODE,
    Key_LMETA,
    Key_RMETA,
    Key_LHYPER,
    Key_RHYPER,
    Key_CAPSLOCK,
    Key_NUMLOCKCLEAR,
    Key_SCROLLLOCK,
    Key_LEVEL5_SHIFT,
    Key_MULTI_KEY_COMPOSE,

    // Regular keys follow
    Key_UNKNOWN,
    Key_RETURN,
    Key_ESCAPE,
    Key_BACKSPACE,
    Key_TAB,
    Key_SPACE,
    Key_EXCLAIM,
    Key_DBLAPOSTROPHE,
    Key_HASH,
    Key_DOLLAR,
    Key_PERCENT,
    Key_AMPERSAND,
    Key_APOSTROPHE,
    Key_LEFTPAREN,
    Key_RIGHTPAREN,
    Key_ASTERISK,
    Key_PLUS,
    Key_COMMA,
    Key_MINUS,
    Key_PERIOD,
    Key_SLASH,
    Key_0,
    Key_1,
    Key_2,
    Key_3,
    Key_4,
    Key_5,
    Key_6,
    Key_7,
    Key_8,
    Key_9,
    Key_COLON,
    Key_SEMICOLON,
    Key_LESS,
    Key_EQUALS,
    Key_GREATER,
    Key_QUESTION,
    Key_AT,
    Key_LEFTBRACKET,
    Key_BACKSLASH,
    Key_RIGHTBRACKET,
    Key_CARET,
    Key_UNDERSCORE,
    Key_GRAVE,
    Key_A,
    Key_B,
    Key_C,
    Key_D,
    Key_E,
    Key_F,
    Key_G,
    Key_H,
    Key_I,
    Key_J,
    Key_K,
    Key_L,
    Key_M,
    Key_N,
    Key_O,
    Key_P,
    Key_Q,
    Key_R,
    Key_S,
    Key_T,
    Key_U,
    Key_V,
    Key_W,
    Key_X,
    Key_Y,
    Key_Z,
    Key_LEFTBRACE,
    Key_PIPE,
    Key_RIGHTBRACE,
    Key_TILDE,
    Key_DELETE,
    Key_PLUSMINUS,
    Key_F1,
    Key_F2,
    Key_F3,
    Key_F4,
    Key_F5,
    Key_F6,
    Key_F7,
    Key_F8,
    Key_F9,
    Key_F10,
    Key_F11,
    Key_F12,
    Key_PRINTSCREEN,
    Key_PAUSE,
    Key_INSERT,
    Key_HOME,
    Key_PAGEUP,
    Key_END,
    Key_PAGEDOWN,
    Key_RIGHT,
    Key_LEFT,
    Key_DOWN,
    Key_UP,
    Key_KP_DIVIDE,
    Key_KP_MULTIPLY,
    Key_KP_MINUS,
    Key_KP_PLUS,
    Key_KP_ENTER,
    Key_KP_1,
    Key_KP_2,
    Key_KP_3,
    Key_KP_4,
    Key_KP_5,
    Key_KP_6,
    Key_KP_7,
    Key_KP_8,
    Key_KP_9,
    Key_KP_0,
    Key_KP_PERIOD,
    Key_APPLICATION,
    Key_POWER,
    Key_KP_EQUALS,
    Key_F13,
    Key_F14,
    Key_F15,
    Key_F16,
    Key_F17,
    Key_F18,
    Key_F19,
    Key_F20,
    Key_F21,
    Key_F22,
    Key_F23,
    Key_F24,
    Key_EXECUTE,
    Key_HELP,
    Key_MENU,
    Key_SELECT,
    Key_STOP,
    Key_AGAIN,
    Key_UNDO,
    Key_CUT,
    Key_COPY,
    Key_PASTE,
    Key_FIND,
    Key_MUTE,
    Key_VOLUMEUP,
    Key_VOLUMEDOWN,
    Key_KP_COMMA,
    Key_KP_EQUALSAS400,
    Key_ALTERASE,
    Key_SYSREQ,
    Key_CANCEL,
    Key_CLEAR,
    Key_PRIOR,
    Key_RETURN2,
    Key_SEPARATOR,
    Key_OUT,
    Key_OPER,
    Key_CLEARAGAIN,
    Key_CRSEL,
    Key_EXSEL,
    Key_KP_00,
    Key_KP_000,
    Key_THOUSANDSSEPARATOR,
    Key_DECIMALSEPARATOR,
    Key_CURRENCYUNIT,
    Key_CURRENCYSUBUNIT,
    Key_KP_LEFTPAREN,
    Key_KP_RIGHTPAREN,
    Key_KP_LEFTBRACE,
    Key_KP_RIGHTBRACE,
    Key_KP_TAB,
    Key_KP_BACKSPACE,
    Key_KP_A,
    Key_KP_B,
    Key_KP_C,
    Key_KP_D,
    Key_KP_E,
    Key_KP_F,
    Key_KP_XOR,
    Key_KP_POWER,
    Key_KP_PERCENT,
    Key_KP_LESS,
    Key_KP_GREATER,
    Key_KP_AMPERSAND,
    Key_KP_DBLAMPERSAND,
    Key_KP_VERTICALBAR,
    Key_KP_DBLVERTICALBAR,
    Key_KP_COLON,
    Key_KP_HASH,
    Key_KP_SPACE,
    Key_KP_AT,
    Key_KP_EXCLAM,
    Key_KP_MEMSTORE,
    Key_KP_MEMRECALL,
    Key_KP_MEMCLEAR,
    Key_KP_MEMADD,
    Key_KP_MEMSUBTRACT,
    Key_KP_MEMMULTIPLY,
    Key_KP_MEMDIVIDE,
    Key_KP_PLUSMINUS,
    Key_KP_CLEAR,
    Key_KP_CLEARENTRY,
    Key_KP_BINARY,
    Key_KP_OCTAL,
    Key_KP_DECIMAL,
    Key_KP_HEXADECIMAL,
    Key_SLEEP,
    Key_WAKE,
    Key_CHANNEL_INCREMENT,
    Key_CHANNEL_DECREMENT,
    Key_MEDIA_PLAY,
    Key_MEDIA_PAUSE,
    Key_MEDIA_RECORD,
    Key_MEDIA_FAST_FORWARD,
    Key_MEDIA_REWIND,
    Key_MEDIA_NEXT_TRACK,
    Key_MEDIA_PREVIOUS_TRACK,
    Key_MEDIA_STOP,
    Key_MEDIA_EJECT,
    Key_MEDIA_PLAY_PAUSE,
    Key_MEDIA_SELECT,
    Key_AC_NEW,
    Key_AC_OPEN,
    Key_AC_CLOSE,
    Key_AC_EXIT,
    Key_AC_SAVE,
    Key_AC_PRINT,
    Key_AC_PROPERTIES,
    Key_AC_SEARCH,
    Key_AC_HOME,
    Key_AC_BACK,
    Key_AC_FORWARD,
    Key_AC_STOP,
    Key_AC_REFRESH,
    Key_AC_BOOKMARKS,
    Key_SOFTLEFT,
    Key_SOFTRIGHT,
    Key_CALL,
    Key_ENDCALL,
    Key_LEFT_TAB,

    // Convert from SDL key code to CustomKey
    pub fn fromSDL(sdl_key: c.sdl.SDL_Keycode) Keys {
        return switch (sdl_key) {
            c.sdl.SDLK_UNKNOWN => .Key_UNKNOWN,
            c.sdl.SDLK_RETURN => .Key_RETURN,
            c.sdl.SDLK_ESCAPE => .Key_ESCAPE,
            c.sdl.SDLK_BACKSPACE => .Key_BACKSPACE,
            c.sdl.SDLK_TAB => .Key_TAB,
            c.sdl.SDLK_SPACE => .Key_SPACE,
            c.sdl.SDLK_EXCLAIM => .Key_EXCLAIM,
            c.sdl.SDLK_DBLAPOSTROPHE => .Key_DBLAPOSTROPHE,
            c.sdl.SDLK_HASH => .Key_HASH,
            c.sdl.SDLK_DOLLAR => .Key_DOLLAR,
            c.sdl.SDLK_PERCENT => .Key_PERCENT,
            c.sdl.SDLK_AMPERSAND => .Key_AMPERSAND,
            c.sdl.SDLK_APOSTROPHE => .Key_APOSTROPHE,
            c.sdl.SDLK_LEFTPAREN => .Key_LEFTPAREN,
            c.sdl.SDLK_RIGHTPAREN => .Key_RIGHTPAREN,
            c.sdl.SDLK_ASTERISK => .Key_ASTERISK,
            c.sdl.SDLK_PLUS => .Key_PLUS,
            c.sdl.SDLK_COMMA => .Key_COMMA,
            c.sdl.SDLK_MINUS => .Key_MINUS,
            c.sdl.SDLK_PERIOD => .Key_PERIOD,
            c.sdl.SDLK_SLASH => .Key_SLASH,
            c.sdl.SDLK_0 => .Key_0,
            c.sdl.SDLK_1 => .Key_1,
            c.sdl.SDLK_2 => .Key_2,
            c.sdl.SDLK_3 => .Key_3,
            c.sdl.SDLK_4 => .Key_4,
            c.sdl.SDLK_5 => .Key_5,
            c.sdl.SDLK_6 => .Key_6,
            c.sdl.SDLK_7 => .Key_7,
            c.sdl.SDLK_8 => .Key_8,
            c.sdl.SDLK_9 => .Key_9,
            c.sdl.SDLK_COLON => .Key_COLON,
            c.sdl.SDLK_SEMICOLON => .Key_SEMICOLON,
            c.sdl.SDLK_LESS => .Key_LESS,
            c.sdl.SDLK_EQUALS => .Key_EQUALS,
            c.sdl.SDLK_GREATER => .Key_GREATER,
            c.sdl.SDLK_QUESTION => .Key_QUESTION,
            c.sdl.SDLK_AT => .Key_AT,
            c.sdl.SDLK_LEFTBRACKET => .Key_LEFTBRACKET,
            c.sdl.SDLK_BACKSLASH => .Key_BACKSLASH,
            c.sdl.SDLK_RIGHTBRACKET => .Key_RIGHTBRACKET,
            c.sdl.SDLK_CARET => .Key_CARET,
            c.sdl.SDLK_UNDERSCORE => .Key_UNDERSCORE,
            c.sdl.SDLK_GRAVE => .Key_GRAVE,
            c.sdl.SDLK_A => .Key_A,
            c.sdl.SDLK_B => .Key_B,
            c.sdl.SDLK_C => .Key_C,
            c.sdl.SDLK_D => .Key_D,
            c.sdl.SDLK_E => .Key_E,
            c.sdl.SDLK_F => .Key_F,
            c.sdl.SDLK_G => .Key_G,
            c.sdl.SDLK_H => .Key_H,
            c.sdl.SDLK_I => .Key_I,
            c.sdl.SDLK_J => .Key_J,
            c.sdl.SDLK_K => .Key_K,
            c.sdl.SDLK_L => .Key_L,
            c.sdl.SDLK_M => .Key_M,
            c.sdl.SDLK_N => .Key_N,
            c.sdl.SDLK_O => .Key_O,
            c.sdl.SDLK_P => .Key_P,
            c.sdl.SDLK_Q => .Key_Q,
            c.sdl.SDLK_R => .Key_R,
            c.sdl.SDLK_S => .Key_S,
            c.sdl.SDLK_T => .Key_T,
            c.sdl.SDLK_U => .Key_U,
            c.sdl.SDLK_V => .Key_V,
            c.sdl.SDLK_W => .Key_W,
            c.sdl.SDLK_X => .Key_X,
            c.sdl.SDLK_Y => .Key_Y,
            c.sdl.SDLK_Z => .Key_Z,
            c.sdl.SDLK_LEFTBRACE => .Key_LEFTBRACE,
            c.sdl.SDLK_PIPE => .Key_PIPE,
            c.sdl.SDLK_RIGHTBRACE => .Key_RIGHTBRACE,
            c.sdl.SDLK_TILDE => .Key_TILDE,
            c.sdl.SDLK_DELETE => .Key_DELETE,
            c.sdl.SDLK_PLUSMINUS => .Key_PLUSMINUS,
            c.sdl.SDLK_CAPSLOCK => .Key_CAPSLOCK,
            c.sdl.SDLK_F1 => .Key_F1,
            c.sdl.SDLK_F2 => .Key_F2,
            c.sdl.SDLK_F3 => .Key_F3,
            c.sdl.SDLK_F4 => .Key_F4,
            c.sdl.SDLK_F5 => .Key_F5,
            c.sdl.SDLK_F6 => .Key_F6,
            c.sdl.SDLK_F7 => .Key_F7,
            c.sdl.SDLK_F8 => .Key_F8,
            c.sdl.SDLK_F9 => .Key_F9,
            c.sdl.SDLK_F10 => .Key_F10,
            c.sdl.SDLK_F11 => .Key_F11,
            c.sdl.SDLK_F12 => .Key_F12,
            c.sdl.SDLK_PRINTSCREEN => .Key_PRINTSCREEN,
            c.sdl.SDLK_SCROLLLOCK => .Key_SCROLLLOCK,
            c.sdl.SDLK_PAUSE => .Key_PAUSE,
            c.sdl.SDLK_INSERT => .Key_INSERT,
            c.sdl.SDLK_HOME => .Key_HOME,
            c.sdl.SDLK_PAGEUP => .Key_PAGEUP,
            c.sdl.SDLK_END => .Key_END,
            c.sdl.SDLK_PAGEDOWN => .Key_PAGEDOWN,
            c.sdl.SDLK_RIGHT => .Key_RIGHT,
            c.sdl.SDLK_LEFT => .Key_LEFT,
            c.sdl.SDLK_DOWN => .Key_DOWN,
            c.sdl.SDLK_UP => .Key_UP,
            c.sdl.SDLK_NUMLOCKCLEAR => .Key_NUMLOCKCLEAR,
            c.sdl.SDLK_KP_DIVIDE => .Key_KP_DIVIDE,
            c.sdl.SDLK_KP_MULTIPLY => .Key_KP_MULTIPLY,
            c.sdl.SDLK_KP_MINUS => .Key_KP_MINUS,
            c.sdl.SDLK_KP_PLUS => .Key_KP_PLUS,
            c.sdl.SDLK_KP_ENTER => .Key_KP_ENTER,
            c.sdl.SDLK_KP_1 => .Key_KP_1,
            c.sdl.SDLK_KP_2 => .Key_KP_2,
            c.sdl.SDLK_KP_3 => .Key_KP_3,
            c.sdl.SDLK_KP_4 => .Key_KP_4,
            c.sdl.SDLK_KP_5 => .Key_KP_5,
            c.sdl.SDLK_KP_6 => .Key_KP_6,
            c.sdl.SDLK_KP_7 => .Key_KP_7,
            c.sdl.SDLK_KP_8 => .Key_KP_8,
            c.sdl.SDLK_KP_9 => .Key_KP_9,
            c.sdl.SDLK_KP_0 => .Key_KP_0,
            c.sdl.SDLK_KP_PERIOD => .Key_KP_PERIOD,
            c.sdl.SDLK_APPLICATION => .Key_APPLICATION,
            c.sdl.SDLK_POWER => .Key_POWER,
            c.sdl.SDLK_KP_EQUALS => .Key_KP_EQUALS,
            c.sdl.SDLK_F13 => .Key_F13,
            c.sdl.SDLK_F14 => .Key_F14,
            c.sdl.SDLK_F15 => .Key_F15,
            c.sdl.SDLK_F16 => .Key_F16,
            c.sdl.SDLK_F17 => .Key_F17,
            c.sdl.SDLK_F18 => .Key_F18,
            c.sdl.SDLK_F19 => .Key_F19,
            c.sdl.SDLK_F20 => .Key_F20,
            c.sdl.SDLK_F21 => .Key_F21,
            c.sdl.SDLK_F22 => .Key_F22,
            c.sdl.SDLK_F23 => .Key_F23,
            c.sdl.SDLK_F24 => .Key_F24,
            c.sdl.SDLK_EXECUTE => .Key_EXECUTE,
            c.sdl.SDLK_HELP => .Key_HELP,
            c.sdl.SDLK_MENU => .Key_MENU,
            c.sdl.SDLK_SELECT => .Key_SELECT,
            c.sdl.SDLK_STOP => .Key_STOP,
            c.sdl.SDLK_AGAIN => .Key_AGAIN,
            c.sdl.SDLK_UNDO => .Key_UNDO,
            c.sdl.SDLK_CUT => .Key_CUT,
            c.sdl.SDLK_COPY => .Key_COPY,
            c.sdl.SDLK_PASTE => .Key_PASTE,
            c.sdl.SDLK_FIND => .Key_FIND,
            c.sdl.SDLK_MUTE => .Key_MUTE,
            c.sdl.SDLK_VOLUMEUP => .Key_VOLUMEUP,
            c.sdl.SDLK_VOLUMEDOWN => .Key_VOLUMEDOWN,
            c.sdl.SDLK_KP_COMMA => .Key_KP_COMMA,
            c.sdl.SDLK_KP_EQUALSAS400 => .Key_KP_EQUALSAS400,
            c.sdl.SDLK_ALTERASE => .Key_ALTERASE,
            c.sdl.SDLK_SYSREQ => .Key_SYSREQ,
            c.sdl.SDLK_CANCEL => .Key_CANCEL,
            c.sdl.SDLK_CLEAR => .Key_CLEAR,
            c.sdl.SDLK_PRIOR => .Key_PRIOR,
            c.sdl.SDLK_RETURN2 => .Key_RETURN2,
            c.sdl.SDLK_SEPARATOR => .Key_SEPARATOR,
            c.sdl.SDLK_OUT => .Key_OUT,
            c.sdl.SDLK_OPER => .Key_OPER,
            c.sdl.SDLK_CLEARAGAIN => .Key_CLEARAGAIN,
            c.sdl.SDLK_CRSEL => .Key_CRSEL,
            c.sdl.SDLK_EXSEL => .Key_EXSEL,
            c.sdl.SDLK_KP_00 => .Key_KP_00,
            c.sdl.SDLK_KP_000 => .Key_KP_000,
            c.sdl.SDLK_THOUSANDSSEPARATOR => .Key_THOUSANDSSEPARATOR,
            c.sdl.SDLK_DECIMALSEPARATOR => .Key_DECIMALSEPARATOR,
            c.sdl.SDLK_CURRENCYUNIT => .Key_CURRENCYUNIT,
            c.sdl.SDLK_CURRENCYSUBUNIT => .Key_CURRENCYSUBUNIT,
            c.sdl.SDLK_KP_LEFTPAREN => .Key_KP_LEFTPAREN,
            c.sdl.SDLK_KP_RIGHTPAREN => .Key_KP_RIGHTPAREN,
            c.sdl.SDLK_KP_LEFTBRACE => .Key_KP_LEFTBRACE,
            c.sdl.SDLK_KP_RIGHTBRACE => .Key_KP_RIGHTBRACE,
            c.sdl.SDLK_KP_TAB => .Key_KP_TAB,
            c.sdl.SDLK_KP_BACKSPACE => .Key_KP_BACKSPACE,
            c.sdl.SDLK_KP_A => .Key_KP_A,
            c.sdl.SDLK_KP_B => .Key_KP_B,
            c.sdl.SDLK_KP_C => .Key_KP_C,
            c.sdl.SDLK_KP_D => .Key_KP_D,
            c.sdl.SDLK_KP_E => .Key_KP_E,
            c.sdl.SDLK_KP_F => .Key_KP_F,
            c.sdl.SDLK_KP_XOR => .Key_KP_XOR,
            c.sdl.SDLK_KP_POWER => .Key_KP_POWER,
            c.sdl.SDLK_KP_PERCENT => .Key_KP_PERCENT,
            c.sdl.SDLK_KP_LESS => .Key_KP_LESS,
            c.sdl.SDLK_KP_GREATER => .Key_KP_GREATER,
            c.sdl.SDLK_KP_AMPERSAND => .Key_KP_AMPERSAND,
            c.sdl.SDLK_KP_DBLAMPERSAND => .Key_KP_DBLAMPERSAND,
            c.sdl.SDLK_KP_VERTICALBAR => .Key_KP_VERTICALBAR,
            c.sdl.SDLK_KP_DBLVERTICALBAR => .Key_KP_DBLVERTICALBAR,
            c.sdl.SDLK_KP_COLON => .Key_KP_COLON,
            c.sdl.SDLK_KP_HASH => .Key_KP_HASH,
            c.sdl.SDLK_KP_SPACE => .Key_KP_SPACE,
            c.sdl.SDLK_KP_AT => .Key_KP_AT,
            c.sdl.SDLK_KP_EXCLAM => .Key_KP_EXCLAM,
            c.sdl.SDLK_KP_MEMSTORE => .Key_KP_MEMSTORE,
            c.sdl.SDLK_KP_MEMRECALL => .Key_KP_MEMRECALL,
            c.sdl.SDLK_KP_MEMCLEAR => .Key_KP_MEMCLEAR,
            c.sdl.SDLK_KP_MEMADD => .Key_KP_MEMADD,
            c.sdl.SDLK_KP_MEMSUBTRACT => .Key_KP_MEMSUBTRACT,
            c.sdl.SDLK_KP_MEMMULTIPLY => .Key_KP_MEMMULTIPLY,
            c.sdl.SDLK_KP_MEMDIVIDE => .Key_KP_MEMDIVIDE,
            c.sdl.SDLK_KP_PLUSMINUS => .Key_KP_PLUSMINUS,
            c.sdl.SDLK_KP_CLEAR => .Key_KP_CLEAR,
            c.sdl.SDLK_KP_CLEARENTRY => .Key_KP_CLEARENTRY,
            c.sdl.SDLK_KP_BINARY => .Key_KP_BINARY,
            c.sdl.SDLK_KP_OCTAL => .Key_KP_OCTAL,
            c.sdl.SDLK_KP_DECIMAL => .Key_KP_DECIMAL,
            c.sdl.SDLK_KP_HEXADECIMAL => .Key_KP_HEXADECIMAL,
            c.sdl.SDLK_LCTRL => .Key_LCTRL,
            c.sdl.SDLK_LSHIFT => .Key_LSHIFT,
            c.sdl.SDLK_LALT => .Key_LALT,
            c.sdl.SDLK_LGUI => .Key_LGUI,
            c.sdl.SDLK_RCTRL => .Key_RCTRL,
            c.sdl.SDLK_RSHIFT => .Key_RSHIFT,
            c.sdl.SDLK_RALT => .Key_RALT,
            c.sdl.SDLK_RGUI => .Key_RGUI,
            c.sdl.SDLK_MODE => .Key_MODE,
            c.sdl.SDLK_SLEEP => .Key_SLEEP,
            c.sdl.SDLK_WAKE => .Key_WAKE,
            c.sdl.SDLK_CHANNEL_INCREMENT => .Key_CHANNEL_INCREMENT,
            c.sdl.SDLK_CHANNEL_DECREMENT => .Key_CHANNEL_DECREMENT,
            c.sdl.SDLK_MEDIA_PLAY => .Key_MEDIA_PLAY,
            c.sdl.SDLK_MEDIA_PAUSE => .Key_MEDIA_PAUSE,
            c.sdl.SDLK_MEDIA_RECORD => .Key_MEDIA_RECORD,
            c.sdl.SDLK_MEDIA_FAST_FORWARD => .Key_MEDIA_FAST_FORWARD,
            c.sdl.SDLK_MEDIA_REWIND => .Key_MEDIA_REWIND,
            c.sdl.SDLK_MEDIA_NEXT_TRACK => .Key_MEDIA_NEXT_TRACK,
            c.sdl.SDLK_MEDIA_PREVIOUS_TRACK => .Key_MEDIA_PREVIOUS_TRACK,
            c.sdl.SDLK_MEDIA_STOP => .Key_MEDIA_STOP,
            c.sdl.SDLK_MEDIA_EJECT => .Key_MEDIA_EJECT,
            c.sdl.SDLK_MEDIA_PLAY_PAUSE => .Key_MEDIA_PLAY_PAUSE,
            c.sdl.SDLK_MEDIA_SELECT => .Key_MEDIA_SELECT,
            c.sdl.SDLK_AC_NEW => .Key_AC_NEW,
            c.sdl.SDLK_AC_OPEN => .Key_AC_OPEN,
            c.sdl.SDLK_AC_CLOSE => .Key_AC_CLOSE,
            c.sdl.SDLK_AC_EXIT => .Key_AC_EXIT,
            c.sdl.SDLK_AC_SAVE => .Key_AC_SAVE,
            c.sdl.SDLK_AC_PRINT => .Key_AC_PRINT,
            c.sdl.SDLK_AC_PROPERTIES => .Key_AC_PROPERTIES,
            c.sdl.SDLK_AC_SEARCH => .Key_AC_SEARCH,
            c.sdl.SDLK_AC_HOME => .Key_AC_HOME,
            c.sdl.SDLK_AC_BACK => .Key_AC_BACK,
            c.sdl.SDLK_AC_FORWARD => .Key_AC_FORWARD,
            c.sdl.SDLK_AC_STOP => .Key_AC_STOP,
            c.sdl.SDLK_AC_REFRESH => .Key_AC_REFRESH,
            c.sdl.SDLK_AC_BOOKMARKS => .Key_AC_BOOKMARKS,
            c.sdl.SDLK_SOFTLEFT => .Key_SOFTLEFT,
            c.sdl.SDLK_SOFTRIGHT => .Key_SOFTRIGHT,
            c.sdl.SDLK_CALL => .Key_CALL,
            c.sdl.SDLK_ENDCALL => .Key_ENDCALL,
            c.sdl.SDLK_LEFT_TAB => .Key_LEFT_TAB,
            c.sdl.SDLK_LEVEL5_SHIFT => .Key_LEVEL5_SHIFT,
            c.sdl.SDLK_MULTI_KEY_COMPOSE => .Key_MULTI_KEY_COMPOSE,
            c.sdl.SDLK_LMETA => .Key_LMETA,
            c.sdl.SDLK_RMETA => .Key_RMETA,
            c.sdl.SDLK_LHYPER => .Key_LHYPER,
            c.sdl.SDLK_RHYPER => .Key_RHYPER,
            else => .Key_UNKNOWN,
        };
    }

    // Convert from CustomKey to SDL key code
    pub fn toSDL(self: Keys) c.sdl.SDL_Keycode {
        return switch (self) {
            .Key_UNKNOWN => c.sdl.SDLK_UNKNOWN,
            .Key_RETURN => c.sdl.SDLK_RETURN,
            .Key_ESCAPE => c.sdl.SDLK_ESCAPE,
            .Key_BACKSPACE => c.sdl.SDLK_BACKSPACE,
            .Key_TAB => c.sdl.SDLK_TAB,
            .Key_SPACE => c.sdl.SDLK_SPACE,
            .Key_EXCLAIM => c.sdl.SDLK_EXCLAIM,
            .Key_DBLAPOSTROPHE => c.sdl.SDLK_DBLAPOSTROPHE,
            .Key_HASH => c.sdl.SDLK_HASH,
            .Key_DOLLAR => c.sdl.SDLK_DOLLAR,
            .Key_PERCENT => c.sdl.SDLK_PERCENT,
            .Key_AMPERSAND => c.sdl.SDLK_AMPERSAND,
            .Key_APOSTROPHE => c.sdl.SDLK_APOSTROPHE,
            .Key_LEFTPAREN => c.sdl.SDLK_LEFTPAREN,
            .Key_RIGHTPAREN => c.sdl.SDLK_RIGHTPAREN,
            .Key_ASTERISK => c.sdl.SDLK_ASTERISK,
            .Key_PLUS => c.sdl.SDLK_PLUS,
            .Key_COMMA => c.sdl.SDLK_COMMA,
            .Key_MINUS => c.sdl.SDLK_MINUS,
            .Key_PERIOD => c.sdl.SDLK_PERIOD,
            .Key_SLASH => c.sdl.SDLK_SLASH,
            .Key_0 => c.sdl.SDLK_0,
            .Key_1 => c.sdl.SDLK_1,
            .Key_2 => c.sdl.SDLK_2,
            .Key_3 => c.sdl.SDLK_3,
            .Key_4 => c.sdl.SDLK_4,
            .Key_5 => c.sdl.SDLK_5,
            .Key_6 => c.sdl.SDLK_6,
            .Key_7 => c.sdl.SDLK_7,
            .Key_8 => c.sdl.SDLK_8,
            .Key_9 => c.sdl.SDLK_9,
            .Key_COLON => c.sdl.SDLK_COLON,
            .Key_SEMICOLON => c.sdl.SDLK_SEMICOLON,
            .Key_LESS => c.sdl.SDLK_LESS,
            .Key_EQUALS => c.sdl.SDLK_EQUALS,
            .Key_GREATER => c.sdl.SDLK_GREATER,
            .Key_QUESTION => c.sdl.SDLK_QUESTION,
            .Key_AT => c.sdl.SDLK_AT,
            .Key_LEFTBRACKET => c.sdl.SDLK_LEFTBRACKET,
            .Key_BACKSLASH => c.sdl.SDLK_BACKSLASH,
            .Key_RIGHTBRACKET => c.sdl.SDLK_RIGHTBRACKET,
            .Key_CARET => c.sdl.SDLK_CARET,
            .Key_UNDERSCORE => c.sdl.SDLK_UNDERSCORE,
            .Key_GRAVE => c.sdl.SDLK_GRAVE,
            .Key_A => c.sdl.SDLK_A,
            .Key_B => c.sdl.SDLK_B,
            .Key_C => c.sdl.SDLK_C,
            .Key_D => c.sdl.SDLK_D,
            .Key_E => c.sdl.SDLK_E,
            .Key_F => c.sdl.SDLK_F,
            .Key_G => c.sdl.SDLK_G,
            .Key_H => c.sdl.SDLK_H,
            .Key_I => c.sdl.SDLK_I,
            .Key_J => c.sdl.SDLK_J,
            .Key_K => c.sdl.SDLK_K,
            .Key_L => c.sdl.SDLK_L,
            .Key_M => c.sdl.SDLK_M,
            .Key_N => c.sdl.SDLK_N,
            .Key_O => c.sdl.SDLK_O,
            .Key_P => c.sdl.SDLK_P,
            .Key_Q => c.sdl.SDLK_Q,
            .Key_R => c.sdl.SDLK_R,
            .Key_S => c.sdl.SDLK_S,
            .Key_T => c.sdl.SDLK_T,
            .Key_U => c.sdl.SDLK_U,
            .Key_V => c.sdl.SDLK_V,
            .Key_W => c.sdl.SDLK_W,
            .Key_X => c.sdl.SDLK_X,
            .Key_Y => c.sdl.SDLK_Y,
            .Key_Z => c.sdl.SDLK_Z,
            .Key_LEFTBRACE => c.sdl.SDLK_LEFTBRACE,
            .Key_PIPE => c.sdl.SDLK_PIPE,
            .Key_RIGHTBRACE => c.sdl.SDLK_RIGHTBRACE,
            .Key_TILDE => c.sdl.SDLK_TILDE,
            .Key_DELETE => c.sdl.SDLK_DELETE,
            .Key_PLUSMINUS => c.sdl.SDLK_PLUSMINUS,
            .Key_CAPSLOCK => c.sdl.SDLK_CAPSLOCK,
            .Key_F1 => c.sdl.SDLK_F1,
            .Key_F2 => c.sdl.SDLK_F2,
            .Key_F3 => c.sdl.SDLK_F3,
            .Key_F4 => c.sdl.SDLK_F4,
            .Key_F5 => c.sdl.SDLK_F5,
            .Key_F6 => c.sdl.SDLK_F6,
            .Key_F7 => c.sdl.SDLK_F7,
            .Key_F8 => c.sdl.SDLK_F8,
            .Key_F9 => c.sdl.SDLK_F9,
            .Key_F10 => c.sdl.SDLK_F10,
            .Key_F11 => c.sdl.SDLK_F11,
            .Key_F12 => c.sdl.SDLK_F12,
            .Key_PRINTSCREEN => c.sdl.SDLK_PRINTSCREEN,
            .Key_SCROLLLOCK => c.sdl.SDLK_SCROLLLOCK,
            .Key_PAUSE => c.sdl.SDLK_PAUSE,
            .Key_INSERT => c.sdl.SDLK_INSERT,
            .Key_HOME => c.sdl.SDLK_HOME,
            .Key_PAGEUP => c.sdl.SDLK_PAGEUP,
            .Key_END => c.sdl.SDLK_END,
            .Key_PAGEDOWN => c.sdl.SDLK_PAGEDOWN,
            .Key_RIGHT => c.sdl.SDLK_RIGHT,
            .Key_LEFT => c.sdl.SDLK_LEFT,
            .Key_DOWN => c.sdl.SDLK_DOWN,
            .Key_UP => c.sdl.SDLK_UP,
            .Key_NUMLOCKCLEAR => c.sdl.SDLK_NUMLOCKCLEAR,
            .Key_KP_DIVIDE => c.sdl.SDLK_KP_DIVIDE,
            .Key_KP_MULTIPLY => c.sdl.SDLK_KP_MULTIPLY,
            .Key_KP_MINUS => c.sdl.SDLK_KP_MINUS,
            .Key_KP_PLUS => c.sdl.SDLK_KP_PLUS,
            .Key_KP_ENTER => c.sdl.SDLK_KP_ENTER,
            .Key_KP_1 => c.sdl.SDLK_KP_1,
            .Key_KP_2 => c.sdl.SDLK_KP_2,
            .Key_KP_3 => c.sdl.SDLK_KP_3,
            .Key_KP_4 => c.sdl.SDLK_KP_4,
            .Key_KP_5 => c.sdl.SDLK_KP_5,
            .Key_KP_6 => c.sdl.SDLK_KP_6,
            .Key_KP_7 => c.sdl.SDLK_KP_7,
            .Key_KP_8 => c.sdl.SDLK_KP_8,
            .Key_KP_9 => c.sdl.SDLK_KP_9,
            .Key_KP_0 => c.sdl.SDLK_KP_0,
            .Key_KP_PERIOD => c.sdl.SDLK_KP_PERIOD,
            .Key_APPLICATION => c.sdl.SDLK_APPLICATION,
            .Key_POWER => c.sdl.SDLK_POWER,
            .Key_KP_EQUALS => c.sdl.SDLK_KP_EQUALS,
            .Key_F13 => c.sdl.SDLK_F13,
            .Key_F14 => c.sdl.SDLK_F14,
            .Key_F15 => c.sdl.SDLK_F15,
            .Key_F16 => c.sdl.SDLK_F16,
            .Key_F17 => c.sdl.SDLK_F17,
            .Key_F18 => c.sdl.SDLK_F18,
            .Key_F19 => c.sdl.SDLK_F19,
            .Key_F20 => c.sdl.SDLK_F20,
            .Key_F21 => c.sdl.SDLK_F21,
            .Key_F22 => c.sdl.SDLK_F22,
            .Key_F23 => c.sdl.SDLK_F23,
            .Key_F24 => c.sdl.SDLK_F24,
            .Key_EXECUTE => c.sdl.SDLK_EXECUTE,
            .Key_HELP => c.sdl.SDLK_HELP,
            .Key_MENU => c.sdl.SDLK_MENU,
            .Key_SELECT => c.sdl.SDLK_SELECT,
            .Key_STOP => c.sdl.SDLK_STOP,
            .Key_AGAIN => c.sdl.SDLK_AGAIN,
            .Key_UNDO => c.sdl.SDLK_UNDO,
            .Key_CUT => c.sdl.SDLK_CUT,
            .Key_COPY => c.sdl.SDLK_COPY,
            .Key_PASTE => c.sdl.SDLK_PASTE,
            .Key_FIND => c.sdl.SDLK_FIND,
            .Key_MUTE => c.sdl.SDLK_MUTE,
            .Key_VOLUMEUP => c.sdl.SDLK_VOLUMEUP,
            .Key_VOLUMEDOWN => c.sdl.SDLK_VOLUMEDOWN,
            .Key_KP_COMMA => c.sdl.SDLK_KP_COMMA,
            .Key_KP_EQUALSAS400 => c.sdl.SDLK_KP_EQUALSAS400,
            .Key_ALTERASE => c.sdl.SDLK_ALTERASE,
            .Key_SYSREQ => c.sdl.SDLK_SYSREQ,
            .Key_CANCEL => c.sdl.SDLK_CANCEL,
            .Key_CLEAR => c.sdl.SDLK_CLEAR,
            .Key_PRIOR => c.sdl.SDLK_PRIOR,
            .Key_RETURN2 => c.sdl.SDLK_RETURN2,
            .Key_SEPARATOR => c.sdl.SDLK_SEPARATOR,
            .Key_OUT => c.sdl.SDLK_OUT,
            .Key_OPER => c.sdl.SDLK_OPER,
            .Key_CLEARAGAIN => c.sdl.SDLK_CLEARAGAIN,
            .Key_CRSEL => c.sdl.SDLK_CRSEL,
            .Key_EXSEL => c.sdl.SDLK_EXSEL,
            .Key_KP_00 => c.sdl.SDLK_KP_00,
            .Key_KP_000 => c.sdl.SDLK_KP_000,
            .Key_THOUSANDSSEPARATOR => c.sdl.SDLK_THOUSANDSSEPARATOR,
            .Key_DECIMALSEPARATOR => c.sdl.SDLK_DECIMALSEPARATOR,
            .Key_CURRENCYUNIT => c.sdl.SDLK_CURRENCYUNIT,
            .Key_CURRENCYSUBUNIT => c.sdl.SDLK_CURRENCYSUBUNIT,
            .Key_KP_LEFTPAREN => c.sdl.SDLK_KP_LEFTPAREN,
            .Key_KP_RIGHTPAREN => c.sdl.SDLK_KP_RIGHTPAREN,
            .Key_KP_LEFTBRACE => c.sdl.SDLK_KP_LEFTBRACE,
            .Key_KP_RIGHTBRACE => c.sdl.SDLK_KP_RIGHTBRACE,
            .Key_KP_TAB => c.sdl.SDLK_KP_TAB,
            .Key_KP_BACKSPACE => c.sdl.SDLK_KP_BACKSPACE,
            .Key_KP_A => c.sdl.SDLK_KP_A,
            .Key_KP_B => c.sdl.SDLK_KP_B,
            .Key_KP_C => c.sdl.SDLK_KP_C,
            .Key_KP_D => c.sdl.SDLK_KP_D,
            .Key_KP_E => c.sdl.SDLK_KP_E,
            .Key_KP_F => c.sdl.SDLK_KP_F,
            .Key_KP_XOR => c.sdl.SDLK_KP_XOR,
            .Key_KP_POWER => c.sdl.SDLK_KP_POWER,
            .Key_KP_PERCENT => c.sdl.SDLK_KP_PERCENT,
            .Key_KP_LESS => c.sdl.SDLK_KP_LESS,
            .Key_KP_GREATER => c.sdl.SDLK_KP_GREATER,
            .Key_KP_AMPERSAND => c.sdl.SDLK_KP_AMPERSAND,
            .Key_KP_DBLAMPERSAND => c.sdl.SDLK_KP_DBLAMPERSAND,
            .Key_KP_VERTICALBAR => c.sdl.SDLK_KP_VERTICALBAR,
            .Key_KP_DBLVERTICALBAR => c.sdl.SDLK_KP_DBLVERTICALBAR,
            .Key_KP_COLON => c.sdl.SDLK_KP_COLON,
            .Key_KP_HASH => c.sdl.SDLK_KP_HASH,
            .Key_KP_SPACE => c.sdl.SDLK_KP_SPACE,
            .Key_KP_AT => c.sdl.SDLK_KP_AT,
            .Key_KP_EXCLAM => c.sdl.SDLK_KP_EXCLAM,
            .Key_KP_MEMSTORE => c.sdl.SDLK_KP_MEMSTORE,
            .Key_KP_MEMRECALL => c.sdl.SDLK_KP_MEMRECALL,
            .Key_KP_MEMCLEAR => c.sdl.SDLK_KP_MEMCLEAR,
            .Key_KP_MEMADD => c.sdl.SDLK_KP_MEMADD,
            .Key_KP_MEMSUBTRACT => c.sdl.SDLK_KP_MEMSUBTRACT,
            .Key_KP_MEMMULTIPLY => c.sdl.SDLK_KP_MEMMULTIPLY,
            .Key_KP_MEMDIVIDE => c.sdl.SDLK_KP_MEMDIVIDE,
            .Key_KP_PLUSMINUS => c.sdl.SDLK_KP_PLUSMINUS,
            .Key_KP_CLEAR => c.sdl.SDLK_KP_CLEAR,
            .Key_KP_CLEARENTRY => c.sdl.SDLK_KP_CLEARENTRY,
            .Key_KP_BINARY => c.sdl.SDLK_KP_BINARY,
            .Key_KP_OCTAL => c.sdl.SDLK_KP_OCTAL,
            .Key_KP_DECIMAL => c.sdl.SDLK_KP_DECIMAL,
            .Key_KP_HEXADECIMAL => c.sdl.SDLK_KP_HEXADECIMAL,
            .Key_LCTRL => c.sdl.SDLK_LCTRL,
            .Key_LSHIFT => c.sdl.SDLK_LSHIFT,
            .Key_LALT => c.sdl.SDLK_LALT,
            .Key_LGUI => c.sdl.SDLK_LGUI,
            .Key_RCTRL => c.sdl.SDLK_RCTRL,
            .Key_RSHIFT => c.sdl.SDLK_RSHIFT,
            .Key_RALT => c.sdl.SDLK_RALT,
            .Key_RGUI => c.sdl.SDLK_RGUI,
            .Key_MODE => c.sdl.SDLK_MODE,
            .Key_SLEEP => c.sdl.SDLK_SLEEP,
            .Key_WAKE => c.sdl.SDLK_WAKE,
            .Key_CHANNEL_INCREMENT => c.sdl.SDLK_CHANNEL_INCREMENT,
            .Key_CHANNEL_DECREMENT => c.sdl.SDLK_CHANNEL_DECREMENT,
            .Key_MEDIA_PLAY => c.sdl.SDLK_MEDIA_PLAY,
            .Key_MEDIA_PAUSE => c.sdl.SDLK_MEDIA_PAUSE,
            .Key_MEDIA_RECORD => c.sdl.SDLK_MEDIA_RECORD,
            .Key_MEDIA_FAST_FORWARD => c.sdl.SDLK_MEDIA_FAST_FORWARD,
            .Key_MEDIA_REWIND => c.sdl.SDLK_MEDIA_REWIND,
            .Key_MEDIA_NEXT_TRACK => c.sdl.SDLK_MEDIA_NEXT_TRACK,
            .Key_MEDIA_PREVIOUS_TRACK => c.sdl.SDLK_MEDIA_PREVIOUS_TRACK,
            .Key_MEDIA_STOP => c.sdl.SDLK_MEDIA_STOP,
            .Key_MEDIA_EJECT => c.sdl.SDLK_MEDIA_EJECT,
            .Key_MEDIA_PLAY_PAUSE => c.sdl.SDLK_MEDIA_PLAY_PAUSE,
            .Key_MEDIA_SELECT => c.sdl.SDLK_MEDIA_SELECT,
            .Key_AC_NEW => c.sdl.SDLK_AC_NEW,
            .Key_AC_OPEN => c.sdl.SDLK_AC_OPEN,
            .Key_AC_CLOSE => c.sdl.SDLK_AC_CLOSE,
            .Key_AC_EXIT => c.sdl.SDLK_AC_EXIT,
            .Key_AC_SAVE => c.sdl.SDLK_AC_SAVE,
            .Key_AC_PRINT => c.sdl.SDLK_AC_PRINT,
            .Key_AC_PROPERTIES => c.sdl.SDLK_AC_PROPERTIES,
            .Key_AC_SEARCH => c.sdl.SDLK_AC_SEARCH,
            .Key_AC_HOME => c.sdl.SDLK_AC_HOME,
            .Key_AC_BACK => c.sdl.SDLK_AC_BACK,
            .Key_AC_FORWARD => c.sdl.SDLK_AC_FORWARD,
            .Key_AC_STOP => c.sdl.SDLK_AC_STOP,
            .Key_AC_REFRESH => c.sdl.SDLK_AC_REFRESH,
            .Key_AC_BOOKMARKS => c.sdl.SDLK_AC_BOOKMARKS,
            .Key_SOFTLEFT => c.sdl.SDLK_SOFTLEFT,
            .Key_SOFTRIGHT => c.sdl.SDLK_SOFTRIGHT,
            .Key_CALL => c.sdl.SDLK_CALL,
            .Key_ENDCALL => c.sdl.SDLK_ENDCALL,
            .Key_LEFT_TAB => c.sdl.SDLK_LEFT_TAB,
            .Key_LEVEL5_SHIFT => c.sdl.SDLK_LEVEL5_SHIFT,
            .Key_MULTI_KEY_COMPOSE => c.sdl.SDLK_MULTI_KEY_COMPOSE,
            .Key_LMETA => c.sdl.SDLK_LMETA,
            .Key_RMETA => c.sdl.SDLK_RMETA,
            .Key_LHYPER => c.sdl.SDLK_LHYPER,
            .Key_RHYPER => c.sdl.SDLK_RHYPER,
            else => .Key_UNKNOWN,
        };
    }

    // Get a human-readable name for the key
    pub fn getName(self: Keys) []const u8 {
        return switch (self) {
            .Key_UNKNOWN => "UNKNOWN",
            .Key_RETURN => "RETURN",
            .Key_ESCAPE => "ESCAPE",
            .Key_BACKSPACE => "BACKSPACE",
            .Key_TAB => "TAB",
            .Key_SPACE => "SPACE",
            .Key_EXCLAIM => "EXCLAIM",
            .Key_DBLAPOSTROPHE => "DBLAPOSTROPHE",
            .Key_HASH => "HASH",
            .Key_DOLLAR => "DOLLAR",
            .Key_PERCENT => "PERCENT",
            .Key_AMPERSAND => "AMPERSAND",
            .Key_APOSTROPHE => "APOSTROPHE",
            .Key_LEFTPAREN => "LEFTPAREN",
            .Key_RIGHTPAREN => "RIGHTPAREN",
            .Key_ASTERISK => "ASTERISK",
            .Key_PLUS => "PLUS",
            .Key_COMMA => "COMMA",
            .Key_MINUS => "MINUS",
            .Key_PERIOD => "PERIOD",
            .Key_SLASH => "SLASH",
            .Key_0 => "0",
            .Key_1 => "1",
            .Key_2 => "2",
            .Key_3 => "3",
            .Key_4 => "4",
            .Key_5 => "5",
            .Key_6 => "6",
            .Key_7 => "7",
            .Key_8 => "8",
            .Key_9 => "9",
            .Key_COLON => "COLON",
            .Key_SEMICOLON => "SEMICOLON",
            .Key_LESS => "LESS",
            .Key_EQUALS => "EQUALS",
            .Key_GREATER => "GREATER",
            .Key_QUESTION => "QUESTION",
            .Key_AT => "AT",
            .Key_LEFTBRACKET => "LEFTBRACKET",
            .Key_BACKSLASH => "BACKSLASH",
            .Key_RIGHTBRACKET => "RIGHTBRACKET",
            .Key_CARET => "CARET",
            .Key_UNDERSCORE => "UNDERSCORE",
            .Key_GRAVE => "GRAVE",
            .Key_A => "A",
            .Key_B => "B",
            .Key_C => "C",
            .Key_D => "D",
            .Key_E => "E",
            .Key_F => "F",
            .Key_G => "G",
            .Key_H => "H",
            .Key_I => "I",
            .Key_J => "J",
            .Key_K => "K",
            .Key_L => "L",
            .Key_M => "M",
            .Key_N => "N",
            .Key_O => "O",
            .Key_P => "P",
            .Key_Q => "Q",
            .Key_R => "R",
            .Key_S => "S",
            .Key_T => "T",
            .Key_U => "U",
            .Key_V => "V",
            .Key_W => "W",
            .Key_X => "X",
            .Key_Y => "Y",
            .Key_Z => "Z",
            .Key_LEFTBRACE => "LEFTBRACE",
            .Key_PIPE => "PIPE",
            .Key_RIGHTBRACE => "RIGHTBRACE",
            .Key_TILDE => "TILDE",
            .Key_DELETE => "DELETE",
            .Key_PLUSMINUS => "PLUSMINUS",
            .Key_CAPSLOCK => "CAPSLOCK",
            .Key_F1 => "F1",
            .Key_F2 => "F2",
            .Key_F3 => "F3",
            .Key_F4 => "F4",
            .Key_F5 => "F5",
            .Key_F6 => "F6",
            .Key_F7 => "F7",
            .Key_F8 => "F8",
            .Key_F9 => "F9",
            .Key_F10 => "F10",
            .Key_F11 => "F11",
            .Key_F12 => "F12",
            .Key_PRINTSCREEN => "PRINTSCREEN",
            .Key_SCROLLLOCK => "SCROLLLOCK",
            .Key_PAUSE => "PAUSE",
            .Key_INSERT => "INSERT",
            .Key_HOME => "HOME",
            .Key_PAGEUP => "PAGEUP",
            .Key_END => "END",
            .Key_PAGEDOWN => "PAGEDOWN",
            .Key_RIGHT => "RIGHT",
            .Key_LEFT => "LEFT",
            .Key_DOWN => "DOWN",
            .Key_UP => "UP",
            .Key_NUMLOCKCLEAR => "NUMLOCKCLEAR",
            .Key_KP_DIVIDE => "KP_DIVIDE",
            .Key_KP_MULTIPLY => "KP_MULTIPLY",
            .Key_KP_MINUS => "KP_MINUS",
            .Key_KP_PLUS => "KP_PLUS",
            .Key_KP_ENTER => "KP_ENTER",
            .Key_KP_1 => "KP_1",
            .Key_KP_2 => "KP_2",
            .Key_KP_3 => "KP_3",
            .Key_KP_4 => "KP_4",
            .Key_KP_5 => "KP_5",
            .Key_KP_6 => "KP_6",
            .Key_KP_7 => "KP_7",
            .Key_KP_8 => "KP_8",
            .Key_KP_9 => "KP_9",
            .Key_KP_0 => "KP_0",
            .Key_KP_PERIOD => "KP_PERIOD",
            .Key_APPLICATION => "APPLICATION",
            .Key_POWER => "POWER",
            .Key_KP_EQUALS => "KP_EQUALS",
            .Key_F13 => "F13",
            .Key_F14 => "F14",
            .Key_F15 => "F15",
            .Key_F16 => "F16",
            .Key_F17 => "F17",
            .Key_F18 => "F18",
            .Key_F19 => "F19",
            .Key_F20 => "F20",
            .Key_F21 => "F21",
            .Key_F22 => "F22",
            .Key_F23 => "F23",
            .Key_F24 => "F24",
            .Key_EXECUTE => "EXECUTE",
            .Key_HELP => "HELP",
            .Key_MENU => "MENU",
            .Key_SELECT => "SELECT",
            .Key_STOP => "STOP",
            .Key_AGAIN => "AGAIN",
            .Key_UNDO => "UNDO",
            .Key_CUT => "CUT",
            .Key_COPY => "COPY",
            .Key_PASTE => "PASTE",
            .Key_FIND => "FIND",
            .Key_MUTE => "MUTE",
            .Key_VOLUMEUP => "VOLUMEUP",
            .Key_VOLUMEDOWN => "VOLUMEDOWN",
            .Key_KP_COMMA => "KP_COMMA",
            .Key_KP_EQUALSAS400 => "KP_EQUALSAS400",
            .Key_ALTERASE => "ALTERASE",
            .Key_SYSREQ => "SYSREQ",
            .Key_CANCEL => "CANCEL",
            .Key_CLEAR => "CLEAR",
            .Key_PRIOR => "PRIOR",
            .Key_RETURN2 => "RETURN2",
            .Key_SEPARATOR => "SEPARATOR",
            .Key_OUT => "OUT",
            .Key_OPER => "OPER",
            .Key_CLEARAGAIN => "CLEARAGAIN",
            .Key_CRSEL => "CRSEL",
            .Key_EXSEL => "EXSEL",
            .Key_KP_00 => "KP_00",
            .Key_KP_000 => "KP_000",
            .Key_THOUSANDSSEPARATOR => "THOUSANDSSEPARATOR",
            .Key_DECIMALSEPARATOR => "DECIMALSEPARATOR",
            .Key_CURRENCYUNIT => "CURRENCYUNIT",
            .Key_CURRENCYSUBUNIT => "CURRENCYSUBUNIT",
            .Key_KP_LEFTPAREN => "KP_LEFTPAREN",
            .Key_KP_RIGHTPAREN => "KP_RIGHTPAREN",
            .Key_KP_LEFTBRACE => "KP_LEFTBRACE",
            .Key_KP_RIGHTBRACE => "KP_RIGHTBRACE",
            .Key_KP_TAB => "KP_TAB",
            .Key_KP_BACKSPACE => "KP_BACKSPACE",
            .Key_KP_A => "KP_A",
            .Key_KP_B => "KP_B",
            .Key_KP_C => "KP_C",
            .Key_KP_D => "KP_D",
            .Key_KP_E => "KP_E",
            .Key_KP_F => "KP_F",
            .Key_KP_XOR => "KP_XOR",
            .Key_KP_POWER => "KP_POWER",
            .Key_KP_PERCENT => "KP_PERCENT",
            .Key_KP_LESS => "KP_LESS",
            .Key_KP_GREATER => "KP_GREATER",
            .Key_KP_AMPERSAND => "KP_AMPERSAND",
            .Key_KP_DBLAMPERSAND => "KP_DBLAMPERSAND",
            .Key_KP_VERTICALBAR => "KP_VERTICALBAR",
            .Key_KP_DBLVERTICALBAR => "KP_DBLVERTICALBAR",
            .Key_KP_COLON => "KP_COLON",
            .Key_KP_HASH => "KP_HASH",
            .Key_KP_SPACE => "KP_SPACE",
            .Key_KP_AT => "KP_AT",
            .Key_KP_EXCLAM => "KP_EXCLAM",
            .Key_KP_MEMSTORE => "KP_MEMSTORE",
            .Key_KP_MEMRECALL => "KP_MEMRECALL",
            .Key_KP_MEMCLEAR => "KP_MEMCLEAR",
            .Key_KP_MEMADD => "KP_MEMADD",
            .Key_KP_MEMSUBTRACT => "KP_MEMSUBTRACT",
            .Key_KP_MEMMULTIPLY => "KP_MEMMULTIPLY",
            .Key_KP_MEMDIVIDE => "KP_MEMDIVIDE",
            .Key_KP_PLUSMINUS => "KP_PLUSMINUS",
            .Key_KP_CLEAR => "KP_CLEAR",
            .Key_KP_CLEARENTRY => "KP_CLEARENTRY",
            .Key_KP_BINARY => "KP_BINARY",
            .Key_KP_OCTAL => "KP_OCTAL",
            .Key_KP_DECIMAL => "KP_DECIMAL",
            .Key_KP_HEXADECIMAL => "KP_HEXADECIMAL",
            .Key_LCTRL => "LCTRL",
            .Key_LSHIFT => "LSHIFT",
            .Key_LALT => "LALT",
            .Key_LGUI => "LGUI",
            .Key_RCTRL => "RCTRL",
            .Key_RSHIFT => "RSHIFT",
            .Key_RALT => "RALT",
            .Key_RGUI => "RGUI",
            .Key_MODE => "MODE",
            .Key_SLEEP => "SLEEP",
            .Key_WAKE => "WAKE",
            .Key_CHANNEL_INCREMENT => "CHANNEL_INCREMENT",
            .Key_CHANNEL_DECREMENT => "CHANNEL_DECREMENT",
            .Key_MEDIA_PLAY => "MEDIA_PLAY",
            .Key_MEDIA_PAUSE => "MEDIA_PAUSE",
            .Key_MEDIA_RECORD => "MEDIA_RECORD",
            .Key_MEDIA_FAST_FORWARD => "MEDIA_FAST_FORWARD",
            .Key_MEDIA_REWIND => "MEDIA_REWIND",
            .Key_MEDIA_NEXT_TRACK => "MEDIA_NEXT_TRACK",
            .Key_MEDIA_PREVIOUS_TRACK => "MEDIA_PREVIOUS_TRACK",
            .Key_MEDIA_STOP => "MEDIA_STOP",
            .Key_MEDIA_EJECT => "MEDIA_EJECT",
            .Key_MEDIA_PLAY_PAUSE => "MEDIA_PLAY_PAUSE",
            .Key_MEDIA_SELECT => "MEDIA_SELECT",
            .Key_AC_NEW => "AC_NEW",
            .Key_AC_OPEN => "AC_OPEN",
            .Key_AC_CLOSE => "AC_CLOSE",
            .Key_AC_EXIT => "AC_EXIT",
            .Key_AC_SAVE => "AC_SAVE",
            .Key_AC_PRINT => "AC_PRINT",
            .Key_AC_PROPERTIES => "AC_PROPERTIES",
            .Key_AC_SEARCH => "AC_SEARCH",
            .Key_AC_HOME => "AC_HOME",
            .Key_AC_BACK => "AC_BACK",
            .Key_AC_FORWARD => "AC_FORWARD",
            .Key_AC_STOP => "AC_STOP",
            .Key_AC_REFRESH => "AC_REFRESH",
            .Key_AC_BOOKMARKS => "AC_BOOKMARKS",
            .Key_SOFTLEFT => "SOFTLEFT",
            .Key_SOFTRIGHT => "SOFTRIGHT",
            .Key_CALL => "CALL",
            .Key_ENDCALL => "ENDCALL",
            .Key_LEFT_TAB => "LEFT_TAB",
            .Key_LEVEL5_SHIFT => "LEVEL5_SHIFT",
            .Key_MULTI_KEY_COMPOSE => "MULTI_KEY_COMPOSE",
            .Key_LMETA => "LMETA",
            .Key_RMETA => "RMETA",
            .Key_LHYPER => "LHYPER",
            .Key_RHYPER => "RHYPER",
        };
    }
};
